acme_project/acme_project/urls.py
from django.views.generic.edit import CreateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth import logout
from django.shortcuts import redirect
from .forms import CustomUserCreationForm
def custom_logout(request):
    logout(request)
    return redirect('login')  # Перенаправление на страницу входа

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('birthday/', include('birthday.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('logout/', custom_logout, name='logout'),
    path(
            'auth/registration/',
            CreateView.as_view(
                template_name='registration/registration_form.html',
                form_class=CustomUserCreationForm,
                success_url=reverse_lazy('pages:homepage'),
            ),
            name='registration',
        ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'core.views.page_not_found'
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acme_project/birthday/urls.py
from django.urls import path

from . import views
app_name = 'birthday'

urlpatterns = [
    path('create/', views.BirthdayCreateView.as_view(), name='create'),
    path('list/', views.BirthdayListView.as_view(), name='list'),
    path('<int:pk>/', views.BirthdayDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.BirthdayUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.BirthdayDeleteView.as_view(), name='delete'),
    path('login_only/', views.simple_view),
    path('<int:pk>/comment/', views.add_comment, name='add_comment'),
]

acme_project/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
]

acme_project/birthday/models.py
from django.db import models
from .validators import real_age
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()

class Tag(models.Model):
    tag = models.CharField('Тег', max_length=20)

    def __str__(self):
        return self.tag

class Birthday(models.Model):
    first_name = models.CharField('Имя', max_length=20)
    last_name = models.CharField('Фамилия', blank=True, help_text='Необязательное поле', max_length=20)
    birthday = models.DateField('Дата рождения', validators=[real_age])
    image = models.ImageField('Фото', upload_to='birthdays_images', blank=True)
    author = models.ForeignKey(User, verbose_name='Автор записи', on_delete=models.CASCADE, null=True)
    tags = models.ManyToManyField(Tag, verbose_name='Теги', blank=True, help_text='Удерживайте Ctrl для выбора нескольких вариантов')

    def get_absolute_url(self):
        return reverse('birthday:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Congratulation(models.Model):
    text = models.TextField("Текст поздравления")
    birthday = models.ForeignKey(Birthday, on_delete=models.CASCADE, related_name='congratulations')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.text

acme_project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    bio = models.TextField('Биография', blank=True)

acme_project/acme_project/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name']  # Укажите нужные поля

acme_project/birthday/forms.py
from django import forms
from .models import Birthday, Congratulation

class BirthdayForms(forms.ModelForm):
    class Meta:
        model = Birthday
        fields = ['first_name', 'last_name', 'birthday', 'image', 'author', 'tags']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

class CongratulationForm(forms.ModelForm):
    class Meta:
        model = Congratulation
        fields = ['text']

acme_project/birthday/views.py
from .forms import BirthdayForms, CongratulationForm
from .models import Birthday
from .utils import calculate_birthday
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied

@login_required
def add_comment(request, pk):
    birthday = get_object_or_404(Birthday, pk=pk)
    form = CongratulationForm(request.POST or None)
    if form.is_valid():
        congratulation = form.save(commit=False)
        congratulation.author = request.user
        congratulation.birthday = birthday
        congratulation.save()
    return redirect('birthday:detail', pk=pk)

@login_required
def simple_view(request):
    return HttpResponse("Страница для залогиненных пользователей")

@login_required
def birthday(request):
    form = BirthdayForms(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        return redirect('birthday:list')
    context = {'form': form}
    return render(request, 'birthday/birthday_form.html', context)  # Укажите правильный шаблон

class BirthdayListView(ListView):
    model = Birthday
    queryset = Birthday.objects.prefetch_related(
        'tags'
    ).select_related('author')
    ordering = 'id'
    paginate_by = 5

class BirthdayMixin:
    model = Birthday
    success_url = reverse_lazy('birthday:list')

class BirthdayCreateView(CreateView, LoginRequiredMixin):
    model = Birthday
    form_class = BirthdayForms

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class BirthdayUpdateView(BirthdayMixin, UpdateView, LoginRequiredMixin):
    form_class = BirthdayForms

    def dispatch(self, request, *args, **kwargs):
        instance = get_object_or_404(Birthday, pk=kwargs['pk'])
        if instance.author != request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class BirthdayDeleteView(BirthdayMixin, DeleteView, LoginRequiredMixin):
    form_class = BirthdayForms

class BirthdayDetailView(DetailView, LoginRequiredMixin):
    model = Birthday

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['birthday_countdown'] = calculate_birthday(self.object.birthday)
        context['form'] = CongratulationForm()
        context['congratulations'] = self.object.congratulations.select_related('author')
        return context

acme_project/core/views.py
from django.shortcuts import render

def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html', status=403)

def page_not_found(request, exception):
    return render(request, 'core/404.html', status=404)

acme_project/pages/views.py
from django.views.generic import TemplateView
class HomePage(TemplateView):
    template_name = 'pages/index.html'

acme_project/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from acme_project.acme_project.forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/registration_form.html'

acme_project/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title>Проект ACME</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <div class="container pt-5">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

acme_project/templates/birthday/birthday_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>Удалить запись {{ object.pk }}</h1>
  <div class="card col-4 m-3">
    <div class="card-header">
      {{ birthday.first_name }} {{ birthday.last_name }} - {{ birthday.birthday }}
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_button button_type="submit" content="Удалить" %}
      </form>
    </div>
  </div>
{% endblock content %} 

acme_project/templates/birthday/birthday_detail.html
{% extends "base.html" %}
<!-- Подгружаем теги для библиотеки django_bootstrap -->
{% load django_bootstrap5 %}

{% block content %}
  ID записи: {{ object.id }}
  <hr>
  {% if birthday.image %}
    <div>
      <img src="{{ birthday.image.url }}" height="200">
    </div>
  {% endif %}
  <h2>Привет, {{ object.first_name }} {{ object.last_name }}</h2>
  {% if birthday_countdown == 0 %}
    <p>С днём рождения!</p>
  {% else %}
    <p>Осталось дней до дня рождения: {{ birthday_countdown }}!</p>
  {% endif %}
  <div>
    <h3>Поздравления:</h3>
    <!-- Если пользователь залогинен, отображаем форму -->
    {% if user.is_authenticated %}
      <!-- Указываем, на какой адрес нужно отправить POST-запрос -->
      <form action="{% url 'birthday:add_comment' object.pk %}" method="post" class="col-3">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Отправить поздравление" %}
      </form>
    {% endif %}
    <!-- В цикле перебираем и выводим поздравления -->
    {% for congratulation in congratulations %}
      <hr>
      <p>
        {{ congratulation.author.username }}
        поздравил {{ congratulation.created_at|date:"d M Y H:i" }}
      </p>
      <p><b>{{ congratulation.text }}</b></p>
    {% endfor %}
  </div>
{% endblock content %} 

acme_project/templates/birthday/birthday_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  {% if "/edit/" in request.path %}
    <h1>Редактировать запись {{ form.instance.pk }}</h1>
  {% else %}
    <h1>Создать запись</h1>
  {% endif %}
  <div class="card col-4">
    <div class="card-header">
      Калькулятор ожидания дня рождения
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Отправить" %}
      </form>
    </div>
  </div>
{% endblock content %}

acme_project/templates/birthday/birthday_list.html
{% extends "base.html" %}

{% block content %}
  {% for birthday in page_obj %}
    <div class="row">

      <div class="col-2">
        {% if birthday.image %}
          <img src="{{ birthday.image.url }}" height=100>
        {% endif %}
      </div>

      <div class="col-10">
      <div>
        {{ birthday.first_name }} {{ birthday.last_name }} - {{ birthday.birthday }}<br>
        <a href="{% url 'birthday:detail' birthday.id %}">Сколько до дня рождения?</a>
      </div>

      <!-- Начало нового блока кода -->
      <div>
        <!-- Чтобы сократить количество кода —
          введём переменную all_tags, в которой будут лежать все теги объекта -->
        {% with all_tags=birthday.tags.all %}
          <!-- Если у записи есть хоть один тег -->
          {% if all_tags %}
            <!-- Выводим теги через запятую, самую первую букву делаем заглавной -->
            {{ all_tags|join:", "|lower|capfirst }}
            <!-- Также выводим username пользователя -->
            пользователя {{ birthday.author.username }}
          {% endif %}
        {% endwith %}
      </div>
      <!-- Конец нового блока кода -->

      {% if birthday.author == user %}
        <div>
          <a href="{% url 'birthday:edit' birthday.id %}">Изменить запись</a>
          | <a href="{% url 'birthday:delete' birthday.id %}">Удалить запись</a>
        </div>
      {% endif %}
    </div>

      {% if not forloop.last %}
        <hr class="mt-3">
      {% endif %}
    </div>
  {% endfor %}
  {% include "includes/paginator.html" %}

{% endblock %} 

acme_project/templates/core/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF. 403{% endblock %}

{% block content %}
  <h1>Ошибка CSRF. 403</h1>
{% endblock %} 

acme_project/templates/includes/header.html
<!-- templates/includes/header.html -->
<header>
  <nav class="navbar shadow-sm">
    <div class="container">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:homepage' %} active {% endif %}"
              href="{% url 'pages:homepage' %}">
              Главная
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'birthday:create' %} active {% endif %}"
              href="{% url 'birthday:create' %}">
              Калькулятор дней рождения
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'birthday:list' %} active {% endif %}" href="{% url 'birthday:list' %}">
              Cписок дней рождения
            </a>
          </li>
          {% if user.is_authenticated %}
            <span class="navbar-text">Пользователь: <b>{{ user.username }}</b></span>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'password_change' %} active {% endif %}"
                href="{% url 'password_change' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'login' %} active {% endif %}" href="{% url 'login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if view_name == 'registration' %} active {% endif %}" href="{% url 'registration' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

acme_project/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination">
      <!-- Если существует предыдущая страница 
           (если мы не на первой странице) 
           рисуем кнопку "Первая страница"... -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <!-- ...и кнопку "Предыдущая" -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      <!-- Перебираем в цикле все номера страниц -->
      {% for i in page_obj.paginator.page_range %}
        <!-- Если номер страницы совпадает с i... -->
        {% if page_obj.number == i %}
          <!-- ..."подсвечиваем" кнопку: ставим класс "active"
               и делаем не ссылку, а span (просто текстовый блок) -->
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <!-- Остальные кнопки отрисовываем без подсветки, со ссылками -->
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <!-- Если существует следующая страница 
           (если мы не на последней странице) 
           рисуем кнопку "Следующая"... -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <!-- ...и кнопку "Последняя" -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %} 

acme_project/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Проект ACME</h1>
  <p>
    Acme Corporation: <b>A</b> <b>C</b>ompany <b>M</b>ade <b>E</b>verything
  </p>
  <div class="row">
    <!-- Добавим колонку "col-3" -->
    <div class="col-3">
      Количество записей о днях рождения<br />в нашем проекте:
    </div>
    <div class="col-9">
      <!-- Добавим колонку "col-9" и выведем значение переменной total_count.
           С помощью стиля Bootstrap отобразим его очень крупным шрифтом  -->
      <div class="display-1">{{ total_count }}</div>
    </div>
  </div>
{% endblock %} 